/**
 * Repository interface for BlockCohortRefresh
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BlockCohortRefreshEntity
} from "../models/block-cohort-refresh.entity.js";
import type {
  DerivedArtefact
} from "../types/index.js";
/**
 * BlockCohortRefreshRepository Interface
 */
export interface BlockCohortRefreshRepository extends CreateReadRepository<BlockCohortRefreshEntity, DerivedArtefact, string, Record<string, never>> {

}
