/**
 * Repository interface for DerivedArtefact
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DerivedArtefactEntity
} from "../models/derived-artefact.entity.js";
import type {
  ListDerivedArtefactsParams,
  DerivedArtefact
} from "../types/index.js";
/**
 * DerivedArtefactRepository Interface
 */
export interface DerivedArtefactRepository extends CreateReadRepository<DerivedArtefactEntity, DerivedArtefact, string, ListDerivedArtefactsParams> {

}
