/**
 * Repository interface for Exempt
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExemptEntity
} from "../models/exempt.entity.js";
import type {
  DerivedArtefact
} from "../types/index.js";
/**
 * ExemptRepository Interface
 */
export interface ExemptRepository extends CreateReadRepository<ExemptEntity, DerivedArtefact, string, Record<string, never>> {

}
