/**
 * Decide Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DecideEntity } from "@erasuremesh/core/exceptions/models/index.js";
import { exceptionsSchemas } from "@erasuremesh/core/exceptions";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exc";

export function createDecide(overrides: Partial<DecideEntity> = {}) {
  const raw = {
    id: overrides.id ?? `exc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    kind: overrides.kind ?? "sla_breach",
    orderId: overrides.orderId ?? `eor_${ulid().toLowerCase()}`,
    rationale: overrides.rationale ?? faker.lorem.word(),
    requestedBy: overrides.requestedBy ?? faker.lorem.word(),
    status: overrides.status ?? "open",
    ...overrides,
  };

  return exceptionsSchemas.ExceptionRecord.parse(raw);
}

export function decideBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDecide(overrides));
}
