/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * RecipientNotices Domain Use Cases
 * 
 * List of all use case names for the recipient-notices domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const RECIPIENTNOTICES_USE_CASES = [
  "executeCreateRecipientNotice",
  "executeListRecipientNotices",
  "executeMarkRecipientNoticeDisproportionate",
  "executeSendRecipientNotice"
] as const;
