/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@erasuremesh/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildDerivedArtefactsDomainModule,
  buildErasureOrdersDomainModule,
  buildEvidencePacksDomainModule,
  buildExceptionsDomainModule,
  buildIdentityDomainModule,
  buildProcessorGraphDomainModule,
  buildRecipientNoticesDomainModule,
} from "../domains/index.js";
import type {
  DerivedArtefactsDomainModule,
  ErasureOrdersDomainModule,
  EvidencePacksDomainModule,
  ExceptionsDomainModule,
  IdentityDomainModule,
  ProcessorGraphDomainModule,
  RecipientNoticesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private derivedArtefactsModule: DerivedArtefactsDomainModule | null = null;
  private erasureOrdersModule: ErasureOrdersDomainModule | null = null;
  private evidencePacksModule: EvidencePacksDomainModule | null = null;
  private exceptionsModule: ExceptionsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private processorGraphModule: ProcessorGraphDomainModule | null = null;
  private recipientNoticesModule: RecipientNoticesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get derived-artefacts domain module
   */
  getDerivedArtefactsDependencies(): DerivedArtefactsDomainModule {
    if (!this.derivedArtefactsModule) {
      this.derivedArtefactsModule = buildDerivedArtefactsDomainModule(this.dynamoClient);
    }
    return this.derivedArtefactsModule;
  }

  /**
   * Get erasure-orders domain module
   */
  getErasureOrdersDependencies(): ErasureOrdersDomainModule {
    if (!this.erasureOrdersModule) {
      this.erasureOrdersModule = buildErasureOrdersDomainModule(this.dynamoClient);
    }
    return this.erasureOrdersModule;
  }

  /**
   * Get evidence-packs domain module
   */
  getEvidencePacksDependencies(): EvidencePacksDomainModule {
    if (!this.evidencePacksModule) {
      this.evidencePacksModule = buildEvidencePacksDomainModule(this.dynamoClient);
    }
    return this.evidencePacksModule;
  }

  /**
   * Get exceptions domain module
   */
  getExceptionsDependencies(): ExceptionsDomainModule {
    if (!this.exceptionsModule) {
      this.exceptionsModule = buildExceptionsDomainModule(this.dynamoClient);
    }
    return this.exceptionsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get processor-graph domain module
   */
  getProcessorGraphDependencies(): ProcessorGraphDomainModule {
    if (!this.processorGraphModule) {
      this.processorGraphModule = buildProcessorGraphDomainModule(this.dynamoClient);
    }
    return this.processorGraphModule;
  }

  /**
   * Get recipient-notices domain module
   */
  getRecipientNoticesDependencies(): RecipientNoticesDomainModule {
    if (!this.recipientNoticesModule) {
      this.recipientNoticesModule = buildRecipientNoticesDomainModule(this.dynamoClient);
    }
    return this.recipientNoticesModule;
  }

  clearDerivedArtefactsDependencies(): void { this.derivedArtefactsModule = null; }
  clearErasureOrdersDependencies(): void { this.erasureOrdersModule = null; }
  clearEvidencePacksDependencies(): void { this.evidencePacksModule = null; }
  clearExceptionsDependencies(): void { this.exceptionsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearProcessorGraphDependencies(): void { this.processorGraphModule = null; }
  clearRecipientNoticesDependencies(): void { this.recipientNoticesModule = null; }

  getDerivedArtefactsDependenciesForRequest(): DerivedArtefactsDomainModule {
    return this.getDerivedArtefactsDependencies();
  }

  getErasureOrdersDependenciesForRequest(): ErasureOrdersDomainModule {
    return this.getErasureOrdersDependencies();
  }

  getEvidencePacksDependenciesForRequest(): EvidencePacksDomainModule {
    return this.getEvidencePacksDependencies();
  }

  getExceptionsDependenciesForRequest(): ExceptionsDomainModule {
    return this.getExceptionsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getProcessorGraphDependenciesForRequest(): ProcessorGraphDomainModule {
    return this.getProcessorGraphDependencies();
  }

  getRecipientNoticesDependenciesForRequest(): RecipientNoticesDomainModule {
    return this.getRecipientNoticesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.derivedArtefactsModule = null;
    this.erasureOrdersModule = null;
    this.evidencePacksModule = null;
    this.exceptionsModule = null;
    this.identityModule = null;
    this.processorGraphModule = null;
    this.recipientNoticesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
