/**
 * CreateVerifySeal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { VerifyEvidencePackSealParams } from "@erasuremesh/core/evidence-packs";

export function createCreateVerifySealRequest(overrides: Partial<VerifyEvidencePackSealParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
