/**
 * ListEdge DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListProcessorGraphEdgesParams } from "@erasuremesh/core/processor-graph";

export function createListEdgeRequest(overrides: Partial<ListProcessorGraphEdgesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
