/**
 * Edge Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/processor-graph.openapi.types.js";
import { schemas } from "../schemas/processor-graph.schemas.js";

/**
 * Entity: EdgeEntity
 * Description: Represents the Edge domain model.
 * Source: schemas.GraphEdge
 * Type: Persisted Entity (x-dynamodb)
 */
export const EdgeEntitySchema = schemas.GraphEdge;
export type EdgeEntity = components["schemas"]["GraphEdge"];
