/**
 * ProcessorNode Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/processor-graph.openapi.types.js";
import { schemas } from "../schemas/processor-graph.schemas.js";

/**
 * Entity: ProcessorNodeEntity
 * Description: Represents the ProcessorNode domain model.
 * Source: schemas.ProcessorNode
 * Type: Persisted Entity (x-dynamodb)
 */
export const ProcessorNodeEntitySchema = schemas.ProcessorNode;
export type ProcessorNodeEntity = components["schemas"]["ProcessorNode"];
