/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * ProcessorGraph Domain Use Cases
 * 
 * List of all use case names for the processor-graph domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PROCESSORGRAPH_USE_CASES = [
  "executeGetProcessorNode",
  "executeLinkProcessorEdge",
  "executeListProcessorGraphEdges",
  "executeListProcessorNodes",
  "executeRegisterProcessorNode",
  "executeTestProcessorNodeAckEndpoint",
  "executeUpdateProcessorNode"
] as const;
