/**
 * ShareRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShareRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ShareRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ShareRepository,
} from "@erasuremesh/services/evidence-packs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ShareRepositoryDdb } from "./share-repository.ddb.js";

/**
 * ShareRepositoryAdapter
 *
 * Implements ShareRepository port for infrastructure layer.
 */
export class ShareRepositoryAdapter implements ShareRepository {
  private readonly ddb: ShareRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ShareRepositoryDdb(this.dynamoClient);
  }

  async shareEvidencePack(input: Parameters<ShareRepository['shareEvidencePack']>[0]): Promise<Awaited<ReturnType<ShareRepository['shareEvidencePack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.shareEvidencePack(input);
  }
}
