/**
 * VerifySealRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerifySealRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VerifySealRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VerifySealRepository,
} from "@erasuremesh/services/evidence-packs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VerifySealRepositoryDdb } from "./verify-seal-repository.ddb.js";

/**
 * VerifySealRepositoryAdapter
 *
 * Implements VerifySealRepository port for infrastructure layer.
 */
export class VerifySealRepositoryAdapter implements VerifySealRepository {
  private readonly ddb: VerifySealRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VerifySealRepositoryDdb(this.dynamoClient);
  }

  async verifyEvidencePackSeal(input: Parameters<VerifySealRepository['verifyEvidencePackSeal']>[0]): Promise<Awaited<ReturnType<VerifySealRepository['verifyEvidencePackSeal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.verifyEvidencePackSeal(input);
  }
}
