/**
 * RecipientNotice DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNotice DTOs
 *
 * DDD: Application DTOs for RecipientNotice use cases.
 */

import type { CreateRecipientNoticeRequestInput, ListRecipientNoticesParams } from "@erasuremesh/core/recipient-notices/types";

export type ListRecipientNoticesInput = ListRecipientNoticesParams;

export type CreateRecipientNoticeInput = CreateRecipientNoticeRequestInput;

export type ListRecipientNoticesOutput = {};

export type CreateRecipientNoticeOutput = {};
