/**
 * ExecuteDispatchErasureOrder - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDispatchErasureOrder Use Case
 *
 * DDD: Application use case for get Dispatch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DispatchErasureOrderInput, DispatchErasureOrderOutput } from "../dto/dispatch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { DispatchRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDispatchErasureOrder {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dispatch: DispatchRepository
  ) {}

  async execute(input: DispatchErasureOrderInput): Promise<DispatchErasureOrderOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.eroId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).orderId) {
      throw new ValidationError("orderId is required");
    }
    const orderId = (input as any).orderId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dispatch.dispatchErasureOrder({ orderId: orderId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${orderId}`);
    }

    return entity as DispatchErasureOrderOutput;
  }
}
