/**
 * ExecuteExtendErasureOrderSla - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExtendErasureOrderSla Use Case
 *
 * DDD: Application use case for get SlaExtension.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExtendErasureOrderSlaInput, ExtendErasureOrderSlaOutput } from "../dto/sla-extension.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { SlaExtensionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteExtendErasureOrderSla {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly slaExtension: SlaExtensionRepository
  ) {}

  async execute(input: ExtendErasureOrderSlaInput): Promise<ExtendErasureOrderSlaOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.eroId();

    // All field names extracted from OpenAPI spec: extendedDueAt, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).orderId) {
      throw new ValidationError("orderId is required");
    }
    const orderId = (input as any).orderId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.slaExtension.extendErasureOrderSla({ orderId: orderId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${orderId}`);
    }

    return entity as ExtendErasureOrderSlaOutput;
  }
}
