/**
 * ExecuteListErasureOrders - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListErasureOrders Use Case
 *
 * DDD: Application use case for list ErasureOrder.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListErasureOrdersInput, ListErasureOrdersOutput } from "../dto/erasure-order.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { ErasureOrderRepository } from "../ports";

export class ExecuteListErasureOrders {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasureOrder: ErasureOrderRepository
  ) {}

  async execute(input: ListErasureOrdersInput): Promise<ListErasureOrdersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.eroId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.erasureOrder.listErasureOrders({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListErasureOrdersOutput;
  }
}
