/**
 * ProcessorNode Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ProcessorNodeEntity } from "@erasuremesh/core/processor-graph/models/index.js";
import { processorGraphSchemas } from "@erasuremesh/core/processor-graph";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pgr";

export function createProcessorNode(overrides: Partial<ProcessorNodeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `pnd_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    critical: overrides.critical ?? faker.datatype.boolean(),
    name: overrides.name ?? faker.person.fullName(),
    role: overrides.role ?? "controller",
    status: overrides.status ?? "active",
    ...overrides,
  };

  return processorGraphSchemas.ProcessorNode.parse(raw);
}

export function processorNodeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createProcessorNode(overrides));
}
