/**
 * CreateComplete DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CompleteErasureOrderParams } from "@erasuremesh/core/erasure-orders";

export function createCreateCompleteRequest(overrides: Partial<CompleteErasureOrderParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
