/**
 * ExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExceptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExceptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExceptionRepository,
} from "@erasuremesh/services/exceptions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExceptionRepositoryDdb } from "./exception-repository.ddb.js";

/**
 * ExceptionRepositoryAdapter
 *
 * Implements ExceptionRepository port for infrastructure layer.
 */
export class ExceptionRepositoryAdapter implements ExceptionRepository {
  private readonly ddb: ExceptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExceptionRepositoryDdb(this.dynamoClient);
  }

  async listExceptions(input: Parameters<ExceptionRepository['listExceptions']>[0]): Promise<Awaited<ReturnType<ExceptionRepository['listExceptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listExceptions(input);
  }

  async createException(input: Parameters<ExceptionRepository['createException']>[0]): Promise<Awaited<ReturnType<ExceptionRepository['createException']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createException(input);
  }

  async getException(input: Parameters<ExceptionRepository['getException']>[0]): Promise<Awaited<ReturnType<ExceptionRepository['getException']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getException(input);
  }
}
