/**
 * CompletionPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompletionPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CompletionPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CompletionPolicyRepository,
} from "@erasuremesh/services/erasure-orders";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CompletionPolicyRepositoryDdb } from "./completion-policy-repository.ddb.js";

/**
 * CompletionPolicyRepositoryAdapter
 *
 * Implements CompletionPolicyRepository port for infrastructure layer.
 */
export class CompletionPolicyRepositoryAdapter implements CompletionPolicyRepository {
  private readonly ddb: CompletionPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CompletionPolicyRepositoryDdb(this.dynamoClient);
  }

  async getErasureOrderCompletionPolicy(input: Parameters<CompletionPolicyRepository['getErasureOrderCompletionPolicy']>[0]): Promise<Awaited<ReturnType<CompletionPolicyRepository['getErasureOrderCompletionPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getErasureOrderCompletionPolicy(input);
  }
}
