/**
 * DispatchRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DispatchRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DispatchRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DispatchRepository,
} from "@erasuremesh/services/erasure-orders";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DispatchRepositoryDdb } from "./dispatch-repository.ddb.js";

/**
 * DispatchRepositoryAdapter
 *
 * Implements DispatchRepository port for infrastructure layer.
 */
export class DispatchRepositoryAdapter implements DispatchRepository {
  private readonly ddb: DispatchRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DispatchRepositoryDdb(this.dynamoClient);
  }

  async dispatchErasureOrder(input: Parameters<DispatchRepository['dispatchErasureOrder']>[0]): Promise<Awaited<ReturnType<DispatchRepository['dispatchErasureOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.dispatchErasureOrder(input);
  }
}
