/**
 * ErasureOrderRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureOrderRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ErasureOrderRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ErasureOrderRepository,
} from "@erasuremesh/services/erasure-orders";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ErasureOrderRepositoryDdb } from "./erasure-order-repository.ddb.js";

/**
 * ErasureOrderRepositoryAdapter
 *
 * Implements ErasureOrderRepository port for infrastructure layer.
 */
export class ErasureOrderRepositoryAdapter implements ErasureOrderRepository {
  private readonly ddb: ErasureOrderRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ErasureOrderRepositoryDdb(this.dynamoClient);
  }

  async listErasureOrders(input: Parameters<ErasureOrderRepository['listErasureOrders']>[0]): Promise<Awaited<ReturnType<ErasureOrderRepository['listErasureOrders']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listErasureOrders(input);
  }

  async createErasureOrder(input: Parameters<ErasureOrderRepository['createErasureOrder']>[0]): Promise<Awaited<ReturnType<ErasureOrderRepository['createErasureOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createErasureOrder(input);
  }

  async getErasureOrder(input: Parameters<ErasureOrderRepository['getErasureOrder']>[0]): Promise<Awaited<ReturnType<ErasureOrderRepository['getErasureOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getErasureOrder(input);
  }
}
