/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./acknowledgement-repository.ddb.js";
export * from "./complete-repository.ddb.js";
export * from "./completion-policy-repository.ddb.js";
export * from "./dispatch-repository.ddb.js";
export * from "./erasure-order-repository.ddb.js";
export * from "./sla-extension-repository.ddb.js";
export * from "./task-repository.ddb.js";
export * from "./acknowledgement-repository.adapter.js";
export * from "./complete-repository.adapter.js";
export * from "./completion-policy-repository.adapter.js";
export * from "./dispatch-repository.adapter.js";
export * from "./erasure-order-repository.adapter.js";
export * from "./sla-extension-repository.adapter.js";
export * from "./task-repository.adapter.js";
