/**
 * SlaExtensionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaExtensionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SlaExtensionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SlaExtensionRepository,
} from "@erasuremesh/services/erasure-orders";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SlaExtensionRepositoryDdb } from "./sla-extension-repository.ddb.js";

/**
 * SlaExtensionRepositoryAdapter
 *
 * Implements SlaExtensionRepository port for infrastructure layer.
 */
export class SlaExtensionRepositoryAdapter implements SlaExtensionRepository {
  private readonly ddb: SlaExtensionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SlaExtensionRepositoryDdb(this.dynamoClient);
  }

  async extendErasureOrderSla(input: Parameters<SlaExtensionRepository['extendErasureOrderSla']>[0]): Promise<Awaited<ReturnType<SlaExtensionRepository['extendErasureOrderSla']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.extendErasureOrderSla(input);
  }
}
