/**
 * TaskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TaskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TaskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TaskRepository,
} from "@erasuremesh/services/erasure-orders";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TaskRepositoryDdb } from "./task-repository.ddb.js";

/**
 * TaskRepositoryAdapter
 *
 * Implements TaskRepository port for infrastructure layer.
 */
export class TaskRepositoryAdapter implements TaskRepository {
  private readonly ddb: TaskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TaskRepositoryDdb(this.dynamoClient);
  }

  async listErasureOrderTasks(input: Parameters<TaskRepository['listErasureOrderTasks']>[0]): Promise<Awaited<ReturnType<TaskRepository['listErasureOrderTasks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listErasureOrderTasks(input);
  }
}
