/**
 * Exceptions Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createException_Body = z
  .object({
    orderId: z.string().regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/),
    kind: z.enum(['sla_breach', 'force_close', 'critical_node_overdue']),
    rationale: z.string().min(1).max(4000),
    remediationPlan: z.string().max(4000).optional(),
    overdueNodeIds: z
      .array(z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/))
      .optional(),
  })
  .passthrough();
const decideException_Body = z
  .object({
    decision: z.enum(['approve', 'deny']),
    decisionRationale: z.string().max(4000).optional(),
    remediationPlan: z.string().max(4000).optional(),
  })
  .passthrough();

export const schemas: any = {
  createException_Body,
  decideException_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/exceptions',
    alias: 'listExceptions',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['open', 'pending_second_approval', 'approved', 'denied'])
          .optional(),
      },
      {
        name: 'orderId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
                  orderId: z.string().regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/),
                  kind: z.enum([
                    'sla_breach',
                    'force_close',
                    'critical_node_overdue',
                  ]),
                  status: z.enum([
                    'open',
                    'pending_second_approval',
                    'approved',
                    'denied',
                  ]),
                  rationale: z.string().min(1).max(4000),
                  remediationPlan: z.string().max(4000).optional(),
                  overdueNodeIds: z
                    .array(z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/))
                    .optional(),
                  requestedBy: z.string(),
                  firstApproverId: z.string().optional(),
                  secondApproverId: z.string().optional(),
                  decisionRationale: z.string().optional(),
                  decidedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/exceptions',
    alias: 'createException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createException_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
            orderId: z.string().regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'sla_breach',
              'force_close',
              'critical_node_overdue',
            ]),
            status: z.enum([
              'open',
              'pending_second_approval',
              'approved',
              'denied',
            ]),
            rationale: z.string().min(1).max(4000),
            remediationPlan: z.string().max(4000).optional(),
            overdueNodeIds: z
              .array(z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            requestedBy: z.string(),
            firstApproverId: z.string().optional(),
            secondApproverId: z.string().optional(),
            decisionRationale: z.string().optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/exceptions/:exceptionId',
    alias: 'getException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'exceptionId',
        type: 'Path',
        schema: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
            orderId: z.string().regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'sla_breach',
              'force_close',
              'critical_node_overdue',
            ]),
            status: z.enum([
              'open',
              'pending_second_approval',
              'approved',
              'denied',
            ]),
            rationale: z.string().min(1).max(4000),
            remediationPlan: z.string().max(4000).optional(),
            overdueNodeIds: z
              .array(z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            requestedBy: z.string(),
            firstApproverId: z.string().optional(),
            secondApproverId: z.string().optional(),
            decisionRationale: z.string().optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/exceptions/:exceptionId/decide',
    alias: 'decideException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: decideException_Body,
      },
      {
        name: 'exceptionId',
        type: 'Path',
        schema: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^exc_[0-9A-HJKMNP-TV-Z]{26}$/),
            orderId: z.string().regex(/^eor_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'sla_breach',
              'force_close',
              'critical_node_overdue',
            ]),
            status: z.enum([
              'open',
              'pending_second_approval',
              'approved',
              'denied',
            ]),
            rationale: z.string().min(1).max(4000),
            remediationPlan: z.string().max(4000).optional(),
            overdueNodeIds: z
              .array(z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            requestedBy: z.string(),
            firstApproverId: z.string().optional(),
            secondApproverId: z.string().optional(),
            decisionRationale: z.string().optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 403,
        description: `Authenticated but not permitted`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
