/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as derivedArtefactsRoutes from "../../domains/derived-artefacts/routes/index.js";
import * as erasureOrdersRoutes from "../../domains/erasure-orders/routes/index.js";
import * as evidencePacksRoutes from "../../domains/evidence-packs/routes/index.js";
import * as exceptionsRoutes from "../../domains/exceptions/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as processorGraphRoutes from "../../domains/processor-graph/routes/index.js";
import * as recipientNoticesRoutes from "../../domains/recipient-notices/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "derived-artefacts", mod: derivedArtefactsRoutes },
  { domain: "erasure-orders", mod: erasureOrdersRoutes },
  { domain: "evidence-packs", mod: evidencePacksRoutes },
  { domain: "exceptions", mod: exceptionsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "processor-graph", mod: processorGraphRoutes },
  { domain: "recipient-notices", mod: recipientNoticesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
