/**
 * Routes for Dispatch
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { dispatchErasureOrder } from "../handlers/dispatch.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dispatchRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-orders/{orderId}/dispatch (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-orders/:orderId/dispatch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { orderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasureOrdersDependenciesForRequest();
        await dispatchErasureOrder(request, reply, deps);
      });
    }
  );


}
