/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { completeRoutes } from "./complete.routes.js";
export { completionPolicyRoutes } from "./completion-policy.routes.js";
export { dispatchRoutes } from "./dispatch.routes.js";
export { erasureOrderRoutes } from "./erasure-order.routes.js";
export { slaExtensionRoutes } from "./sla-extension.routes.js";
export { taskRoutes } from "./task.routes.js";
export { acknowledgementRoutes } from "./acknowledgement.routes.js";
