/**
 * Dispatch Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/erasure-orders.openapi.types.js";
import { schemas } from "../schemas/erasure-orders.schemas.js";

/**
 * Entity: DispatchEntity
 * Description: Represents the Dispatch domain model.
 * Source: schemas.ErasureOrder
 * Type: Persisted Entity (x-dynamodb)
 */
export const DispatchEntitySchema = schemas.ErasureOrder;
export type DispatchEntity = components["schemas"]["ErasureOrder"];
