/**
 * ExecuteRegisterDerivedArtefact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterDerivedArtefact Use Case
 *
 * DDD: Application use case for create DerivedArtefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterDerivedArtefactInput, RegisterDerivedArtefactOutput } from "../dto/derived-artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { DerivedArtefactRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterDerivedArtefact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly derivedArtefact: DerivedArtefactRepository
  ) {}

  async execute(input: RegisterDerivedArtefactInput): Promise<RegisterDerivedArtefactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.darId();

    // All field names extracted from OpenAPI spec: artefactType, orderId, subjectRef, systemName
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.orderId) {
      throw new ValidationError("orderId is required");
    }
    if (!input.subjectRef) {
      throw new ValidationError("subjectRef is required");
    }
    if (!input.artefactType) {
      throw new ValidationError("artefactType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (derived-artefacts domain)
    const entityId = this.idGenerator.darId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.derivedArtefact.registerDerivedArtefact({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterDerivedArtefactOutput;
  }
}
