/**
 * ExecuteGetDerivedArtefact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDerivedArtefact Use Case
 *
 * DDD: Application use case for get DerivedArtefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDerivedArtefactInput, GetDerivedArtefactOutput } from "../dto/derived-artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { DerivedArtefactRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDerivedArtefact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly derivedArtefact: DerivedArtefactRepository
  ) {}

  async execute(input: GetDerivedArtefactInput): Promise<GetDerivedArtefactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.darId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artefactId) {
      throw new ValidationError("artefactId is required");
    }
    const artefactId = (input as any).artefactId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.derivedArtefact.getDerivedArtefact({ artefactId: artefactId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artefactId}`);
    }

    return entity as GetDerivedArtefactOutput;
  }
}
