/**
 * ExecuteListDerivedArtefacts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDerivedArtefacts Use Case
 *
 * DDD: Application use case for list DerivedArtefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDerivedArtefactsInput, ListDerivedArtefactsOutput } from "../dto/derived-artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { DerivedArtefactRepository } from "../ports";

export class ExecuteListDerivedArtefacts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly derivedArtefact: DerivedArtefactRepository
  ) {}

  async execute(input: ListDerivedArtefactsInput): Promise<ListDerivedArtefactsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.darId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.derivedArtefact.listDerivedArtefacts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDerivedArtefactsOutput;
  }
}
