/**
 * Repository interface for Acknowledgement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AcknowledgementEntity
} from "../models/acknowledgement.entity.js";
import type {
  ErasureTask
} from "../types/index.js";
/**
 * AcknowledgementRepository Interface
 */
export interface AcknowledgementRepository extends CreateReadRepository<AcknowledgementEntity, ErasureTask, string, Record<string, never>> {

}
