/**
 * Repository interface for SlaExtension
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SlaExtensionEntity
} from "../models/sla-extension.entity.js";
import type {
  ErasureOrder
} from "../types/index.js";
/**
 * SlaExtensionRepository Interface
 */
export interface SlaExtensionRepository extends CreateReadRepository<SlaExtensionEntity, ErasureOrder, string, Record<string, never>> {

}
