/**
 * Repository interface for Task
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TaskEntity
} from "../models/task.entity.js";
import type {
  ListErasureOrderTasksParams
} from "../types/index.js";
/**
 * TaskRepository Interface
 */
export interface TaskRepository extends ReadRepository<TaskEntity, string, ListErasureOrderTasksParams> {

}
