/**
 * RecipientNotices DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNotices Domain Module - Composition root
 *
 * DDD: Composition root for recipient-notices domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisproportionateEffortRepositoryAdapter,
  RecipientNoticeRepositoryAdapter,
  SendRepositoryAdapter,
} from "@erasuremesh/adapters/recipient-notices";
import { getIdGeneratorService } from "@erasuremesh/adapters";
import type { AdapterDynamoDBClient } from "@erasuremesh/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateRecipientNotice,
  ExecuteListRecipientNotices,
  ExecuteMarkRecipientNoticeDisproportionate,
  ExecuteSendRecipientNotice,
} from "@erasuremesh/services/recipient-notices/usecases";
// Ports (interfaces)
import type {
  DisproportionateEffortRepository,
  RecipientNoticeRepository,
  SendRepository,
} from "@erasuremesh/services/recipient-notices/ports";

export interface RecipientNoticesDomainModule {
  repos: {
    disproportionateEfforts: DisproportionateEffortRepository;
    recipientNotices: RecipientNoticeRepository;
    sends: SendRepository;
  };
  useCases: {
    disproportionateEfforts: {
      get: ExecuteMarkRecipientNoticeDisproportionate;
    };
    recipientNotices: {
      create: ExecuteCreateRecipientNotice;
      list: ExecuteListRecipientNotices;
    };
    sends: {
      create: ExecuteSendRecipientNotice;
    };
  };
}

export function buildRecipientNoticesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RecipientNoticesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disproportionateEfforts?: DisproportionateEffortRepository;
      recipientNotices?: RecipientNoticeRepository;
      sends?: SendRepository;
    } = {};

    obj.disproportionateEfforts = new DisproportionateEffortRepositoryAdapter(dynamoClient);
    obj.recipientNotices = new RecipientNoticeRepositoryAdapter(dynamoClient);
    obj.sends = new SendRepositoryAdapter(dynamoClient);
    return {
      disproportionateEfforts: obj.disproportionateEfforts!,
      recipientNotices: obj.recipientNotices!,
      sends: obj.sends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disproportionateEfforts: {
      get: new ExecuteMarkRecipientNoticeDisproportionate(executionContext, idGenerator, repos.disproportionateEfforts),
    },
    recipientNotices: {
      create: new ExecuteCreateRecipientNotice(executionContext, idGenerator, repos.recipientNotices),
      list: new ExecuteListRecipientNotices(executionContext, idGenerator, repos.recipientNotices),
    },
    sends: {
      create: new ExecuteSendRecipientNotice(executionContext, idGenerator, repos.sends),
    },
  };
  return { repos, useCases: useCases as RecipientNoticesDomainModule["useCases"] };
}
