/**
 * Routes for TestAcknowledgementEndpoint
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { testProcessorNodeAckEndpoint } from "../handlers/test-acknowledgement-endpoint.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function testAcknowledgementEndpointRoutes(fastify: FastifyInstance) {
  // POST /v1/processor-nodes/{nodeId}/test-acknowledgement-endpoint (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/processor-nodes/:nodeId/test-acknowledgement-endpoint",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { nodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProcessorGraphDependenciesForRequest();
        await testProcessorNodeAckEndpoint(request, reply, deps);
      });
    }
  );


}
