/**
 * ListErasureOrderTasks handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listErasureOrderTasks } from "@erasuremesh/api-server/domains/erasure-orders/handlers";
import type { ErasureOrdersDDDDependencies } from "@erasuremesh/api-server/domains/erasure-orders";
import { createTask as createTaskEntity } from "@erasuremesh/factories/erasure-orders";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { ERASUREORDERS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListErasureOrderTasks", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ErasureOrdersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ErasureOrdersDDDDependencies>(
      ERASUREORDERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createTaskEntity({ orgId }),
      createTaskEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListErasureOrderTasks, "execute").mockResolvedValue(useCaseResult);

    await listErasureOrderTasks(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListErasureOrderTasks.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
