/**
 * DisproportionateEffortRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisproportionateEffortRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisproportionateEffortRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisproportionateEffortRepository,
} from "@erasuremesh/services/recipient-notices";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisproportionateEffortRepositoryDdb } from "./disproportionate-effort-repository.ddb.js";

/**
 * DisproportionateEffortRepositoryAdapter
 *
 * Implements DisproportionateEffortRepository port for infrastructure layer.
 */
export class DisproportionateEffortRepositoryAdapter implements DisproportionateEffortRepository {
  private readonly ddb: DisproportionateEffortRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisproportionateEffortRepositoryDdb(this.dynamoClient);
  }

  async markRecipientNoticeDisproportionate(input: Parameters<DisproportionateEffortRepository['markRecipientNoticeDisproportionate']>[0]): Promise<Awaited<ReturnType<DisproportionateEffortRepository['markRecipientNoticeDisproportionate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.markRecipientNoticeDisproportionate(input);
  }
}
