/**
 * Handlers for Send
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RecipientNoticesDomainModule } from "../dependencies/recipient-notices-ddd.dependencies.js";
import type { SendRecipientNoticeInput } from "@erasuremesh/services/recipient-notices";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/recipient-notices/{noticeId}/send
 * Operation: sendRecipientNotice
 */
export async function sendRecipientNotice(
  request: FastifyRequest<{ Params: { noticeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RecipientNoticesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SendRecipientNoticeInput = {
    noticeId: request.params.noticeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.sends.create.execute(input);
  return reply.code(200).send(result);
}


