/**
 * ProcessorGraph DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProcessorGraph Domain Module - Composition root
 *
 * DDD: Composition root for processor-graph domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EdgeRepositoryAdapter,
  ProcessorNodeRepositoryAdapter,
} from "@erasuremesh/adapters/processor-graph";
import { getIdGeneratorService } from "@erasuremesh/adapters";
import type { AdapterDynamoDBClient } from "@erasuremesh/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetProcessorNode,
  ExecuteLinkProcessorEdge,
  ExecuteListProcessorGraphEdges,
  ExecuteListProcessorNodes,
  ExecuteRegisterProcessorNode,
  ExecuteUpdateProcessorNode,
} from "@erasuremesh/services/processor-graph/usecases";
// Ports (interfaces)
import type {
  EdgeRepository,
  ProcessorNodeRepository,
} from "@erasuremesh/services/processor-graph/ports";

export interface ProcessorGraphDomainModule {
  repos: {
    edges: EdgeRepository;
    processorNodes: ProcessorNodeRepository;
  };
  useCases: {
    edges: {
      get: ExecuteLinkProcessorEdge;
      list: ExecuteListProcessorGraphEdges;
    };
    processorNodes: {
      create: ExecuteRegisterProcessorNode;
      get: ExecuteGetProcessorNode;
      list: ExecuteListProcessorNodes;
      update: ExecuteUpdateProcessorNode;
    };
  };
}

export function buildProcessorGraphDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProcessorGraphDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      edges?: EdgeRepository;
      processorNodes?: ProcessorNodeRepository;
    } = {};

    obj.edges = new EdgeRepositoryAdapter(dynamoClient);
    obj.processorNodes = new ProcessorNodeRepositoryAdapter(dynamoClient);
    return {
      edges: obj.edges!,
      processorNodes: obj.processorNodes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    edges: {
      get: new ExecuteLinkProcessorEdge(executionContext, idGenerator, repos.edges),
      list: new ExecuteListProcessorGraphEdges(executionContext, idGenerator, repos.edges),
    },
    processorNodes: {
      create: new ExecuteRegisterProcessorNode(executionContext, idGenerator, repos.processorNodes),
      get: new ExecuteGetProcessorNode(executionContext, idGenerator, repos.processorNodes),
      list: new ExecuteListProcessorNodes(executionContext, idGenerator, repos.processorNodes),
      update: new ExecuteUpdateProcessorNode(executionContext, idGenerator, repos.processorNodes),
    },
  };
  return { repos, useCases: useCases as ProcessorGraphDomainModule["useCases"] };
}
