/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @erasuremesh/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@erasuremesh/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@erasuremesh/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@erasuremesh/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@erasuremesh/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@erasuremesh/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _derivedArtefacts from "./derived-artefacts/index.js";
import * as _erasureOrders from "./erasure-orders/index.js";
import * as _evidencePacks from "./evidence-packs/index.js";
import * as _exceptions from "./exceptions/index.js";
import * as _identity from "./identity/index.js";
import * as _processorGraph from "./processor-graph/index.js";
import * as _recipientNotices from "./recipient-notices/index.js";

// Export as namespaces
export const _shared = __shared;
export const derivedArtefacts = _derivedArtefacts;
export const erasureOrders = _erasureOrders;
export const evidencePacks = _evidencePacks;
export const exceptions = _exceptions;
export const identity = _identity;
export const processorGraph = _processorGraph;
export const recipientNotices = _recipientNotices;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@erasuremesh/core"; activity.types.*
//   - Direct exports: import * from "@erasuremesh/core/activity/types/index.js"
//   - Direct exports: import * from "@erasuremesh/core/activity/repositories/index.js"
//   - Direct exports: import * from "@erasuremesh/core/activity/models/index.js"
//   - Direct exports: import * from "@erasuremesh/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// DerivedArtefacts Service
export { schemas as DerivedArtefactsSchemas } from "./derived-artefacts/schemas/derived-artefacts.schemas.js";

// ErasureOrders Service
export { schemas as ErasureOrdersSchemas } from "./erasure-orders/schemas/erasure-orders.schemas.js";

// EvidencePacks Service
export { schemas as EvidencePacksSchemas } from "./evidence-packs/schemas/evidence-packs.schemas.js";

// Exceptions Service
export { schemas as ExceptionsSchemas } from "./exceptions/schemas/exceptions.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// ProcessorGraph Service
export { schemas as ProcessorGraphSchemas } from "./processor-graph/schemas/processor-graph.schemas.js";

// RecipientNotices Service
export { schemas as RecipientNoticesSchemas } from "./recipient-notices/schemas/recipient-notices.schemas.js";

