/**
 * Exception DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exception DTOs
 *
 * DDD: Application DTOs for Exception use cases.
 */

import type { CreateExceptionRequestInput, GetExceptionParams, ListExceptionsParams } from "@erasuremesh/core/exceptions/types";

export type ListExceptionsInput = ListExceptionsParams;

export type CreateExceptionInput = CreateExceptionRequestInput;

export type GetExceptionInput = GetExceptionParams;

export type ListExceptionsOutput = {};

export type CreateExceptionOutput = {};

export type GetExceptionOutput = {};
