/**
 * AcknowledgementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcknowledgementRepository Port
 *
 * DDD: Application port for acknowledgementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcknowledgeErasureTaskInput, AcknowledgeErasureTaskOutput } from "../dto/acknowledgement.dto";
export interface AcknowledgementRepository {
  acknowledgeErasureTask(input: AcknowledgeErasureTaskInput): Promise<AcknowledgeErasureTaskOutput>;
}

export type { AcknowledgeErasureTaskInput, AcknowledgeErasureTaskOutput } from "../dto/acknowledgement.dto";
