/**
 * CompletionPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompletionPolicyRepository Port
 *
 * DDD: Application port for completionpolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetErasureOrderCompletionPolicyInput, GetErasureOrderCompletionPolicyOutput } from "../dto/completion-policy.dto";
export interface CompletionPolicyRepository {
  getErasureOrderCompletionPolicy(input: GetErasureOrderCompletionPolicyInput): Promise<GetErasureOrderCompletionPolicyOutput>;
}

export type { GetErasureOrderCompletionPolicyInput, GetErasureOrderCompletionPolicyOutput } from "../dto/completion-policy.dto";
