/**
 * CompleteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompleteRepository Port
 *
 * DDD: Application port for completerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CompleteErasureOrderInput, CompleteErasureOrderOutput } from "../dto/complete.dto";
export interface CompleteRepository {
  completeErasureOrder(input: CompleteErasureOrderInput): Promise<CompleteErasureOrderOutput>;
}

export type { CompleteErasureOrderInput, CompleteErasureOrderOutput } from "../dto/complete.dto";
