/**
 * DispatchRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DispatchRepository Port
 *
 * DDD: Application port for dispatchrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DispatchErasureOrderInput, DispatchErasureOrderOutput } from "../dto/dispatch.dto";
export interface DispatchRepository {
  dispatchErasureOrder(input: DispatchErasureOrderInput): Promise<DispatchErasureOrderOutput>;
}

export type { DispatchErasureOrderInput, DispatchErasureOrderOutput } from "../dto/dispatch.dto";
