/**
 * ErasureOrderRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureOrderRepository Port
 *
 * DDD: Application port for erasureorderrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateErasureOrderInput, CreateErasureOrderOutput, GetErasureOrderInput, GetErasureOrderOutput, ListErasureOrdersInput, ListErasureOrdersOutput } from "../dto/erasure-order.dto";
export interface ErasureOrderRepository {
  listErasureOrders(input: ListErasureOrdersInput): Promise<ListErasureOrdersOutput>;
  createErasureOrder(input: CreateErasureOrderInput): Promise<CreateErasureOrderOutput>;
  getErasureOrder(input: GetErasureOrderInput): Promise<GetErasureOrderOutput>;
}

export type { CreateErasureOrderInput, CreateErasureOrderOutput, GetErasureOrderInput, GetErasureOrderOutput, ListErasureOrdersInput, ListErasureOrdersOutput } from "../dto/erasure-order.dto";
