/**
 * EdgeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EdgeRepository Port
 *
 * DDD: Application port for edgerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { LinkProcessorEdgeInput, LinkProcessorEdgeOutput, ListProcessorGraphEdgesInput, ListProcessorGraphEdgesOutput } from "../dto/edge.dto";
export interface EdgeRepository {
  listProcessorGraphEdges(input: ListProcessorGraphEdgesInput): Promise<ListProcessorGraphEdgesOutput>;
  linkProcessorEdge(input: LinkProcessorEdgeInput): Promise<LinkProcessorEdgeOutput>;
}

export type { LinkProcessorEdgeInput, LinkProcessorEdgeOutput, ListProcessorGraphEdgesInput, ListProcessorGraphEdgesOutput } from "../dto/edge.dto";
