/**
 * TestAcknowledgementEndpointRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TestAcknowledgementEndpointRepository Port
 *
 * DDD: Application port for testacknowledgementendpointrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { TestProcessorNodeAckEndpointInput, TestProcessorNodeAckEndpointOutput } from "../dto/test-acknowledgement-endpoint.dto";
export interface TestAcknowledgementEndpointRepository {
  testProcessorNodeAckEndpoint(input: TestProcessorNodeAckEndpointInput): Promise<TestProcessorNodeAckEndpointOutput>;
}

export type { TestProcessorNodeAckEndpointInput, TestProcessorNodeAckEndpointOutput } from "../dto/test-acknowledgement-endpoint.dto";
