/**
 * EvidencePackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePackRepository Port
 *
 * DDD: Application port for evidencepackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssembleEvidencePackInput, AssembleEvidencePackOutput, GetEvidencePackInput, GetEvidencePackOutput, ListEvidencePacksInput, ListEvidencePacksOutput } from "../dto/evidence-pack.dto";
export interface EvidencePackRepository {
  listEvidencePacks(input: ListEvidencePacksInput): Promise<ListEvidencePacksOutput>;
  getEvidencePack(input: GetEvidencePackInput): Promise<GetEvidencePackOutput>;
  assembleEvidencePack(input: AssembleEvidencePackInput): Promise<AssembleEvidencePackOutput>;
}

export type { AssembleEvidencePackInput, AssembleEvidencePackOutput, GetEvidencePackInput, GetEvidencePackOutput, ListEvidencePacksInput, ListEvidencePacksOutput } from "../dto/evidence-pack.dto";
