/**
 * SealRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SealRepository Port
 *
 * DDD: Application port for sealrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SealEvidencePackInput, SealEvidencePackOutput } from "../dto/seal.dto";
export interface SealRepository {
  sealEvidencePack(input: SealEvidencePackInput): Promise<SealEvidencePackOutput>;
}

export type { SealEvidencePackInput, SealEvidencePackOutput } from "../dto/seal.dto";
