/**
 * ShareRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShareRepository Port
 *
 * DDD: Application port for sharerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ShareEvidencePackInput, ShareEvidencePackOutput } from "../dto/share.dto";
export interface ShareRepository {
  shareEvidencePack(input: ShareEvidencePackInput): Promise<ShareEvidencePackOutput>;
}

export type { ShareEvidencePackInput, ShareEvidencePackOutput } from "../dto/share.dto";
