/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./acknowledgement-endpoint-repository.ddb.js";
export * from "./edge-repository.ddb.js";
export * from "./processor-node-repository.ddb.js";
export * from "./edge-repository.adapter.js";
export * from "./processor-node-repository.adapter.js";
export * from "./test-acknowledgement-endpoint-repository.adapter.js";
