/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the recipient-notices domain.
 * Use these factories in tests to create test data.
 */

export { createDisproportionateEffort } from "./disproportionate-effort/entity/disproportionate-effort.entity.factory.js";
export { createRecipientNotice } from "./recipient-notice/entity/recipient-notice.entity.factory.js";
export { createSend } from "./send/entity/send.entity.factory.js";
