/**
 * DisproportionateEffortRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisproportionateEffortRepository Port
 *
 * DDD: Application port for disproportionateeffortrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { MarkRecipientNoticeDisproportionateInput, MarkRecipientNoticeDisproportionateOutput } from "../dto/disproportionate-effort.dto";
export interface DisproportionateEffortRepository {
  markRecipientNoticeDisproportionate(input: MarkRecipientNoticeDisproportionateInput): Promise<MarkRecipientNoticeDisproportionateOutput>;
}

export type { MarkRecipientNoticeDisproportionateInput, MarkRecipientNoticeDisproportionateOutput } from "../dto/disproportionate-effort.dto";
