/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-derived-artefact.handler.test.js";
export * from "./list-derived-artefacts.handler.test.js";
export * from "./register-derived-artefact.handler.test.js";
