/**
 * ListDerivedArtefacts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDerivedArtefacts } from "@erasuremesh/api-server/domains/derived-artefacts/handlers";
import type { DerivedArtefactsDDDDependencies } from "@erasuremesh/api-server/domains/derived-artefacts";
import { createDerivedArtefact as createDerivedArtefactEntity } from "@erasuremesh/factories/derived-artefacts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { DERIVEDARTEFACTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDerivedArtefacts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DerivedArtefactsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DerivedArtefactsDDDDependencies>(
      DERIVEDARTEFACTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDerivedArtefactEntity({ orgId }),
      createDerivedArtefactEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDerivedArtefacts, "execute").mockResolvedValue(useCaseResult);

    await listDerivedArtefacts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDerivedArtefacts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
