/**
 * RegisterDerivedArtefact handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerDerivedArtefact } from "@erasuremesh/api-server/domains/derived-artefacts/handlers";
import type { DerivedArtefactsDDDDependencies } from "@erasuremesh/api-server/domains/derived-artefacts";
import { createDerivedArtefact as createDerivedArtefactEntity } from "@erasuremesh/factories/derived-artefacts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { DERIVEDARTEFACTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterDerivedArtefact", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DerivedArtefactsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DerivedArtefactsDDDDependencies>(
      DERIVEDARTEFACTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDerivedArtefactEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterDerivedArtefact, "execute").mockResolvedValue(useCaseResult);

    await registerDerivedArtefact(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterDerivedArtefact.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
