/**
 * Handlers for Seal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidencePacksDomainModule } from "../dependencies/evidence-packs-ddd.dependencies.js";
import type { SealEvidencePackInput } from "@erasuremesh/services/evidence-packs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/evidence-packs/{packId}/seal
 * Operation: sealEvidencePack
 */
export async function sealEvidencePack(
  request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidencePacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SealEvidencePackInput = {
    packId: request.params.packId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.seals.get.execute(input);
  return reply.code(200).send(result);
}


