/**
 * ListProcessorNodes handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listProcessorNodes } from "@erasuremesh/api-server/domains/processor-graph/handlers";
import type { ProcessorGraphDDDDependencies } from "@erasuremesh/api-server/domains/processor-graph";
import { createProcessorNode as createProcessorNodeEntity } from "@erasuremesh/factories/processor-graph";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { PROCESSORGRAPH_USE_CASES } from "../__factories__/use-cases.js";

describe("ListProcessorNodes", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProcessorGraphDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProcessorGraphDDDDependencies>(
      PROCESSORGRAPH_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createProcessorNodeEntity({ orgId }),
      createProcessorNodeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListProcessorNodes, "execute").mockResolvedValue(useCaseResult);

    await listProcessorNodes(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListProcessorNodes.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
