/**
 * BlockCohortRefresh Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/derived-artefacts.openapi.types.js";
import { schemas } from "../schemas/derived-artefacts.schemas.js";

/**
 * Entity: BlockCohortRefreshEntity
 * Description: Represents the BlockCohortRefresh domain model.
 * Source: schemas.DerivedArtefact
 * Type: Persisted Entity (x-dynamodb)
 */
export const BlockCohortRefreshEntitySchema = schemas.DerivedArtefact;
export type BlockCohortRefreshEntity = components["schemas"]["DerivedArtefact"];
