/**
 * Handlers for DerivedArtefact
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DerivedArtefactsDomainModule } from "../dependencies/derived-artefacts-ddd.dependencies.js";
import type { GetDerivedArtefactInput, ListDerivedArtefactsInput, RegisterDerivedArtefactInput } from "@erasuremesh/services/derived-artefacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/derived-artefacts
 * Operation: listDerivedArtefacts
 */
export async function listDerivedArtefacts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], orderId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DerivedArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDerivedArtefactsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.derivedArtefacts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/derived-artefacts
 * Operation: registerDerivedArtefact
 */
export async function registerDerivedArtefact(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DerivedArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterDerivedArtefactInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.derivedArtefacts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/derived-artefacts/{artefactId}
 * Operation: getDerivedArtefact
 */
export async function getDerivedArtefact(
  request: FastifyRequest<{ Params: { artefactId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DerivedArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDerivedArtefactInput = {
    artefactId: request.params.artefactId,
  };
  const result = await deps.useCases.derivedArtefacts.get.execute(input);
  return reply.code(200).send(result);
}


