/**
 * Handlers for Exempt
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DerivedArtefactsDomainModule } from "../dependencies/derived-artefacts-ddd.dependencies.js";
import type { ExemptDerivedArtefactInput } from "@erasuremesh/services/derived-artefacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/derived-artefacts/{artefactId}/exempt
 * Operation: exemptDerivedArtefact
 */
export async function exemptDerivedArtefact(
  request: FastifyRequest<{ Params: { artefactId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DerivedArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExemptDerivedArtefactInput = {
    artefactId: request.params.artefactId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exempts.get.execute(input);
  return reply.code(200).send(result);
}


