/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the erasure-orders domain.
 * Use these factories in tests to create test data.
 */

export { createAcknowledgement } from "./acknowledgement/entity/acknowledgement.entity.factory.js";
export { createComplete } from "./complete/entity/complete.entity.factory.js";
export { createCreateCompleteRequest } from "./complete/dto/create-complete.dto.factory.js";
export { createCreateDispatchRequest } from "./dispatch/dto/create-dispatch.dto.factory.js";
export { createDispatch } from "./dispatch/entity/dispatch.entity.factory.js";
export { createErasureOrder } from "./erasure-order/entity/erasure-order.entity.factory.js";
export { createSlaExtension } from "./sla-extension/entity/sla-extension.entity.factory.js";
export { createTask } from "./task/entity/task.entity.factory.js";
