/**
 * Edge Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { EdgeEntity } from "@erasuremesh/core/processor-graph/models/index.js";
import { processorGraphSchemas } from "@erasuremesh/core/processor-graph";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pgr";

export function createEdge(overrides: Partial<EdgeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ged_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    contractualRole: overrides.contractualRole ?? "controller",
    fromNodeId: overrides.fromNodeId ?? `pnd_${ulid().toLowerCase()}`,
    toNodeId: overrides.toNodeId ?? `pnd_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return processorGraphSchemas.GraphEdge.parse(raw);
}

export function edgeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEdge(overrides));
}
