/**
 * Handlers for TestAcknowledgementEndpoint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProcessorGraphDomainModule } from "../dependencies/processor-graph-ddd.dependencies.js";
import type { TestProcessorNodeAckEndpointInput } from "@erasuremesh/services/processor-graph";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/processor-nodes/{nodeId}/test-acknowledgement-endpoint
 * Operation: testProcessorNodeAckEndpoint
 */
export async function testProcessorNodeAckEndpoint(
  request: FastifyRequest<{ Params: { nodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProcessorGraphDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: TestProcessorNodeAckEndpointInput = {
    nodeId: request.params.nodeId,
  };
  const result = await deps.useCases.testAcknowledgementEndpoints.get.execute(input);
  return reply.code(200).send(result);
}


