/**
 * ProcessorGraph Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const registerProcessorNode_Body = z
  .object({
    name: z.string().min(1).max(200),
    role: z.enum(['controller', 'processor', 'sub_processor']),
    critical: z.boolean().optional().default(false),
    acknowledgementEndpoint: z.string().url().optional(),
    contactEmail: z.string().email().optional(),
  })
  .passthrough();
const updateProcessorNode_Body = z
  .object({
    name: z.string().min(1).max(200),
    status: z.enum(['active', 'suspended']),
    critical: z.boolean(),
    acknowledgementEndpoint: z.string().url(),
    contactEmail: z.string().email(),
  })
  .partial()
  .passthrough();
const linkProcessorEdge_Body = z
  .object({
    fromNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
    toNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
    contractualRole: z.enum(['controller', 'processor', 'joint']),
    contractualBasis: z.string().max(500).optional(),
  })
  .passthrough();

export const schemas: any = {
  registerProcessorNode_Body,
  updateProcessorNode_Body,
  linkProcessorEdge_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/processor-graph/edges',
    alias: 'listProcessorGraphEdges',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^ged_[0-9A-HJKMNP-TV-Z]{26}$/),
                  fromNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
                  toNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
                  contractualRole: z.enum(['controller', 'processor', 'joint']),
                  contractualBasis: z.string().max(500).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/processor-graph/edges',
    alias: 'linkProcessorEdge',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: linkProcessorEdge_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ged_[0-9A-HJKMNP-TV-Z]{26}$/),
            fromNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            toNodeId: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            contractualRole: z.enum(['controller', 'processor', 'joint']),
            contractualBasis: z.string().max(500).optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/processor-nodes',
    alias: 'listProcessorNodes',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['active', 'suspended']).optional(),
      },
      {
        name: 'critical',
        type: 'Query',
        schema: z.boolean().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string().min(1).max(200),
                  role: z.enum(['controller', 'processor', 'sub_processor']),
                  status: z.enum(['active', 'suspended']),
                  critical: z.boolean().default(false),
                  acknowledgementEndpoint: z.string().url().optional(),
                  contactEmail: z.string().email().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/processor-nodes',
    alias: 'registerProcessorNode',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerProcessorNode_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string().min(1).max(200),
            role: z.enum(['controller', 'processor', 'sub_processor']),
            status: z.enum(['active', 'suspended']),
            critical: z.boolean().default(false),
            acknowledgementEndpoint: z.string().url().optional(),
            contactEmail: z.string().email().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/processor-nodes/:nodeId',
    alias: 'getProcessorNode',
    requestFormat: 'json',
    parameters: [
      {
        name: 'nodeId',
        type: 'Path',
        schema: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string().min(1).max(200),
            role: z.enum(['controller', 'processor', 'sub_processor']),
            status: z.enum(['active', 'suspended']),
            critical: z.boolean().default(false),
            acknowledgementEndpoint: z.string().url().optional(),
            contactEmail: z.string().email().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/processor-nodes/:nodeId',
    alias: 'updateProcessorNode',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateProcessorNode_Body,
      },
      {
        name: 'nodeId',
        type: 'Path',
        schema: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string().min(1).max(200),
            role: z.enum(['controller', 'processor', 'sub_processor']),
            status: z.enum(['active', 'suspended']),
            critical: z.boolean().default(false),
            acknowledgementEndpoint: z.string().url().optional(),
            contactEmail: z.string().email().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/processor-nodes/:nodeId/test-acknowledgement-endpoint',
    alias: 'testProcessorNodeAckEndpoint',
    requestFormat: 'json',
    parameters: [
      {
        name: 'nodeId',
        type: 'Path',
        schema: z.string().regex(/^pnd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            ok: z.boolean(),
            statusCode: z.number().int().optional(),
            detail: z.string().optional(),
            testedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
