/**
 * ListRecipientNotice DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRecipientNoticesParams } from "@erasuremesh/core/recipient-notices";

export function createListRecipientNoticeRequest(overrides: Partial<ListRecipientNoticesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
