/**
 * SendRecipientNotice handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { sendRecipientNotice } from "@erasuremesh/api-server/domains/recipient-notices/handlers";
import type { RecipientNoticesDDDDependencies } from "@erasuremesh/api-server/domains/recipient-notices";
import { createSend as createSendEntity } from "@erasuremesh/factories/recipient-notices";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { RECIPIENTNOTICES_USE_CASES } from "../__factories__/use-cases.js";

describe("SendRecipientNotice", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RecipientNoticesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RecipientNoticesDDDDependencies>(
      RECIPIENTNOTICES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSendEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSendRecipientNotice, "execute").mockResolvedValue(useCaseResult);

    await sendRecipientNotice(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSendRecipientNotice.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
