/**
 * ExemptRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExemptRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExemptRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExemptRepository,
} from "@erasuremesh/services/derived-artefacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExemptRepositoryDdb } from "./exempt-repository.ddb.js";

/**
 * ExemptRepositoryAdapter
 *
 * Implements ExemptRepository port for infrastructure layer.
 */
export class ExemptRepositoryAdapter implements ExemptRepository {
  private readonly ddb: ExemptRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExemptRepositoryDdb(this.dynamoClient);
  }

  async exemptDerivedArtefact(input: Parameters<ExemptRepository['exemptDerivedArtefact']>[0]): Promise<Awaited<ReturnType<ExemptRepository['exemptDerivedArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.exemptDerivedArtefact(input);
  }
}
