/**
 * PurgeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PurgeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PurgeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PurgeRepository,
} from "@erasuremesh/services/derived-artefacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PurgeRepositoryDdb } from "./purge-repository.ddb.js";

/**
 * PurgeRepositoryAdapter
 *
 * Implements PurgeRepository port for infrastructure layer.
 */
export class PurgeRepositoryAdapter implements PurgeRepository {
  private readonly ddb: PurgeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PurgeRepositoryDdb(this.dynamoClient);
  }

  async purgeDerivedArtefact(input: Parameters<PurgeRepository['purgeDerivedArtefact']>[0]): Promise<Awaited<ReturnType<PurgeRepository['purgeDerivedArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.purgeDerivedArtefact(input);
  }
}
