/**
 * DerivedArtefactRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DerivedArtefactRepository Port
 *
 * DDD: Application port for derivedartefactrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDerivedArtefactInput, GetDerivedArtefactOutput, ListDerivedArtefactsInput, ListDerivedArtefactsOutput, RegisterDerivedArtefactInput, RegisterDerivedArtefactOutput } from "../dto/derived-artefact.dto";
export interface DerivedArtefactRepository {
  listDerivedArtefacts(input: ListDerivedArtefactsInput): Promise<ListDerivedArtefactsOutput>;
  registerDerivedArtefact(input: RegisterDerivedArtefactInput): Promise<RegisterDerivedArtefactOutput>;
  getDerivedArtefact(input: GetDerivedArtefactInput): Promise<GetDerivedArtefactOutput>;
}

export type { GetDerivedArtefactInput, GetDerivedArtefactOutput, ListDerivedArtefactsInput, ListDerivedArtefactsOutput, RegisterDerivedArtefactInput, RegisterDerivedArtefactOutput } from "../dto/derived-artefact.dto";
