/**
 * Acknowledgement Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AcknowledgementEntity } from "@erasuremesh/core/erasure-orders/models/index.js";
import { erasureOrdersSchemas } from "@erasuremesh/core/erasure-orders";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ero";

export function createAcknowledgement(overrides: Partial<AcknowledgementEntity> = {}) {
  const raw = {
    id: overrides.id ?? `etk_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    critical: overrides.critical ?? faker.datatype.boolean(),
    orderId: overrides.orderId ?? `eor_${ulid().toLowerCase()}`,
    processorNodeId: overrides.processorNodeId ?? `pnd_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return erasureOrdersSchemas.ErasureTask.parse(raw);
}

export function acknowledgementBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAcknowledgement(overrides));
}
