/**
 * EvidencePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePack DTOs
 *
 * DDD: Application DTOs for EvidencePack use cases.
 */

import type { AssembleEvidencePackParams, GetEvidencePackParams, ListEvidencePacksParams } from "@erasuremesh/core/evidence-packs/types";

export type ListEvidencePacksInput = ListEvidencePacksParams;

export type GetEvidencePackInput = GetEvidencePackParams;

export type AssembleEvidencePackInput = AssembleEvidencePackParams;

export type ListEvidencePacksOutput = {};

export type GetEvidencePackOutput = {};

export type AssembleEvidencePackOutput = {};
