/**
 * Share DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Share DTOs
 *
 * DDD: Application DTOs for Share use cases.
 */

import type { ShareEvidencePackParams, ShareEvidencePackRequestInput } from "@erasuremesh/core/evidence-packs/types";

export type ShareEvidencePackInput = ShareEvidencePackParams & ShareEvidencePackRequestInput;

export type ShareEvidencePackOutput = {};
