/**
 * Send Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SendEntity } from "@erasuremesh/core/recipient-notices/models/index.js";
import { recipientNoticesSchemas } from "@erasuremesh/core/recipient-notices";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rcn";

export function createSend(overrides: Partial<SendEntity> = {}) {
  const raw = {
    id: overrides.id ?? `rcn_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    orderId: overrides.orderId ?? `eor_${ulid().toLowerCase()}`,
    recipientNodeId: overrides.recipientNodeId ?? `pnd_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return recipientNoticesSchemas.RecipientNotice.parse(raw);
}

export function sendBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSend(overrides));
}
