/**
 * Handlers for ErasureOrder
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ErasureOrdersDomainModule } from "../dependencies/erasure-orders-ddd.dependencies.js";
import type { CreateErasureOrderInput, GetErasureOrderInput, ListErasureOrdersInput } from "@erasuremesh/services/erasure-orders";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-orders
 * Operation: listErasureOrders
 */
export async function listErasureOrders(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], tenantId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasureOrdersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListErasureOrdersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.erasureOrders.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasure-orders
 * Operation: createErasureOrder
 */
export async function createErasureOrder(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ErasureOrdersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateErasureOrderInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.erasureOrders.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/erasure-orders/{orderId}
 * Operation: getErasureOrder
 */
export async function getErasureOrder(
  request: FastifyRequest<{ Params: { orderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasureOrdersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetErasureOrderInput = {
    orderId: request.params.orderId,
  };
  const result = await deps.useCases.erasureOrders.get.execute(input);
  return reply.code(200).send(result);
}


