/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./acknowledgement.handlers.js";
export * from "./complete.handlers.js";
export * from "./completion-policy.handlers.js";
export * from "./dispatch.handlers.js";
export * from "./erasure-order.handlers.js";
export * from "./sla-extension.handlers.js";
export * from "./task.handlers.js";
