/**
 * Handlers for Task
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ErasureOrdersDomainModule } from "../dependencies/erasure-orders-ddd.dependencies.js";
import type { ListErasureOrderTasksInput } from "@erasuremesh/services/erasure-orders";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-orders/{orderId}/tasks
 * Operation: listErasureOrderTasks
 */
export async function listErasureOrderTasks(
  request: FastifyRequest<{ Params: { orderId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasureOrdersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListErasureOrderTasksInput = {
    orderId: request.params.orderId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.tasks.list.execute(input);
  return reply.code(200).send(result);
}


