/**
 * AssembleEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { assembleEvidencePack } from "@erasuremesh/api-server/domains/evidence-packs/handlers";
import type { EvidencePacksDDDDependencies } from "@erasuremesh/api-server/domains/evidence-packs";
import { createEvidencePack as createEvidencePackEntity } from "@erasuremesh/factories/evidence-packs";
import { createCreateEvidencePackRequest } from "@erasuremesh/factories/evidence-packs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { EVIDENCEPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("AssembleEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidencePacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidencePacksDDDDependencies>(
      EVIDENCEPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateEvidencePackRequest();
    const entity = createEvidencePackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAssembleEvidencePack, "execute").mockResolvedValue(useCaseResult);

    await assembleEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAssembleEvidencePack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
