/**
 * Handlers for Decide
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ExceptionsDomainModule } from "../dependencies/exceptions-ddd.dependencies.js";
import type { DecideExceptionInput } from "@erasuremesh/services/exceptions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/exceptions/{exceptionId}/decide
 * Operation: decideException
 */
export async function decideException(
  request: FastifyRequest<{ Params: { exceptionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExceptionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideExceptionInput = {
    exceptionId: request.params.exceptionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decides.get.execute(input);
  return reply.code(200).send(result);
}


