/**
 * ExecuteListProcessorNodes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListProcessorNodes Use Case
 *
 * DDD: Application use case for list ProcessorNode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListProcessorNodesInput, ListProcessorNodesOutput } from "../dto/processor-node.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { ProcessorNodeRepository } from "../ports";

export class ExecuteListProcessorNodes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly processorNode: ProcessorNodeRepository
  ) {}

  async execute(input: ListProcessorNodesInput): Promise<ListProcessorNodesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pgrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.processorNode.listProcessorNodes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListProcessorNodesOutput;
  }
}
