/**
 * CompletionPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompletionPolicy DTOs
 *
 * DDD: Application DTOs for CompletionPolicy use cases.
 */

import type { GetErasureOrderCompletionPolicyParams } from "@erasuremesh/core/erasure-orders/types";

export type GetErasureOrderCompletionPolicyInput = GetErasureOrderCompletionPolicyParams;

export type GetErasureOrderCompletionPolicyOutput = {};
