/**
 * Complete DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Complete DTOs
 *
 * DDD: Application DTOs for Complete use cases.
 */

import type { CompleteErasureOrderParams } from "@erasuremesh/core/erasure-orders/types";

export type CompleteErasureOrderInput = CompleteErasureOrderParams;

export type CompleteErasureOrderOutput = {};
