/**
 * SlaExtension DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaExtension DTOs
 *
 * DDD: Application DTOs for SlaExtension use cases.
 */

import type { ExtendErasureOrderSlaParams, ExtendErasureOrderSlaRequestInput } from "@erasuremesh/core/erasure-orders/types";

export type ExtendErasureOrderSlaInput = ExtendErasureOrderSlaParams & ExtendErasureOrderSlaRequestInput;

export type ExtendErasureOrderSlaOutput = {};
