/**
 * Exempt DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: derived-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exempt DTOs
 *
 * DDD: Application DTOs for Exempt use cases.
 */

import type { ExemptDerivedArtefactParams, ExemptDerivedArtefactRequestInput } from "@erasuremesh/core/derived-artefacts/types";

export type ExemptDerivedArtefactInput = ExemptDerivedArtefactParams & ExemptDerivedArtefactRequestInput;

export type ExemptDerivedArtefactOutput = {};
