/**
 * Routes for VerifySeal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { verifyEvidencePackSeal } from "../handlers/verify-seal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function verifySealRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence-packs/{packId}/verify-seal (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence-packs/:packId/verify-seal",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidencePacksDependenciesForRequest();
        await verifyEvidencePackSeal(request, reply, deps);
      });
    }
  );


}
