/**
 * CreateException handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createException } from "@erasuremesh/api-server/domains/exceptions/handlers";
import type { ExceptionsDDDDependencies } from "@erasuremesh/api-server/domains/exceptions";
import { createException as createExceptionEntity } from "@erasuremesh/factories/exceptions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { EXCEPTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateException", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExceptionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExceptionsDDDDependencies>(
      EXCEPTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createExceptionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateException, "execute").mockResolvedValue(useCaseResult);

    await createException(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateException.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
