/**
 * ProcessorNode DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: processor-graph
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProcessorNode DTOs
 *
 * DDD: Application DTOs for ProcessorNode use cases.
 */

import type { GetProcessorNodeParams, ListProcessorNodesParams, RegisterProcessorNodeRequestInput, UpdateProcessorNodeParams, UpdateProcessorNodeRequestInput } from "@erasuremesh/core/processor-graph/types";

export type ListProcessorNodesInput = ListProcessorNodesParams;

export type RegisterProcessorNodeInput = RegisterProcessorNodeRequestInput;

export type GetProcessorNodeInput = GetProcessorNodeParams;

export type UpdateProcessorNodeInput = UpdateProcessorNodeParams & UpdateProcessorNodeRequestInput;

export type ListProcessorNodesOutput = {};

export type RegisterProcessorNodeOutput = {};

export type GetProcessorNodeOutput = {};

export type UpdateProcessorNodeOutput = {};
