/**
 * ExecuteGetException - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetException Use Case
 *
 * DDD: Application use case for get Exception.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExceptionInput, GetExceptionOutput } from "../dto/exception.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { ExceptionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetException {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exception: ExceptionRepository
  ) {}

  async execute(input: GetExceptionInput): Promise<GetExceptionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.excId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).exceptionId) {
      throw new ValidationError("exceptionId is required");
    }
    const exceptionId = (input as any).exceptionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exception.getException({ exceptionId: exceptionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${exceptionId}`);
    }

    return entity as GetExceptionOutput;
  }
}
