/**
 * ExecuteListExceptions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListExceptions Use Case
 *
 * DDD: Application use case for list Exception.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListExceptionsInput, ListExceptionsOutput } from "../dto/exception.dto";
import type { ExecutionContextService, IdGeneratorService } from "@erasuremesh/services/_shared/index.js";
import type { ExceptionRepository } from "../ports";

export class ExecuteListExceptions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exception: ExceptionRepository
  ) {}

  async execute(input: ListExceptionsInput): Promise<ListExceptionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.excId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exception.listExceptions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListExceptionsOutput;
  }
}
