/**
 * CreateErasureOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasure-orders
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createErasureOrder } from "@erasuremesh/api-server/domains/erasure-orders/handlers";
import type { ErasureOrdersDDDDependencies } from "@erasuremesh/api-server/domains/erasure-orders";
import { createErasureOrder as createErasureOrderEntity } from "@erasuremesh/factories/erasure-orders";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@erasuremesh/tests/shared";
import { ERASUREORDERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateErasureOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ErasureOrdersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ErasureOrdersDDDDependencies>(
      ERASUREORDERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createErasureOrderEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateErasureOrder, "execute").mockResolvedValue(useCaseResult);

    await createErasureOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateErasureOrder.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
