/**
 * Repository interface for RecipientNotice
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RecipientNoticeEntity
} from "../models/recipient-notice.entity.js";
import type {
  ListRecipientNoticesParams,
  RecipientNotice
} from "../types/index.js";
/**
 * RecipientNoticeRepository Interface
 */
export interface RecipientNoticeRepository extends CreateReadRepository<RecipientNoticeEntity, RecipientNotice, string, ListRecipientNoticesParams> {

}
