/**
 * Repository interface for Send
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: recipient-notices
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SendEntity
} from "../models/send.entity.js";
import type {
  RecipientNotice
} from "../types/index.js";
/**
 * SendRepository Interface
 */
export interface SendRepository extends CreateReadRepository<SendEntity, RecipientNotice, string, Record<string, never>> {

}
