/**
 * Repository interface for Decide
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: exceptions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DecideEntity
} from "../models/decide.entity.js";
import type {
  ExceptionRecord
} from "../types/index.js";
/**
 * DecideRepository Interface
 */
export interface DecideRepository extends CreateReadRepository<DecideEntity, ExceptionRecord, string, Record<string, never>> {

}
